README.md

This way of installation is meant mostly for Go developers who don’t want to use Docker for one reason or another.

README.md: Describe installation using `go install`

---

README.md

The most important badge is the one with a link to the Go package reference.

README.md: Add some badges

---

README.md

Use the badge provided by pkg.go.dev instead of shields.io. It is more likely Go developers will recognize it. The cost is small graphical inconsistency.

README.md: Replace the reference badge

---

README.md

`docker compose` command is not available on every installation.
`docker-compose` is more common IMHO.

README: Replace `docker compose` with `docker-compose`

---

client/client.go

Some fields in ClientConfig are never used.

client: Remove unused configuration fields

---

client/message_handlers.go
client/subscribe_transaction.go

According to the MQTT specification:
> If a Server receives a SUBSCRIBE Packet containing a Topic Filter that is identical to an existing Subscription’s Topic Filter then it MUST completely replace that existing Subscription with a new Subscription.
This certainly wasn't the case with a slice based store, where new
handlers were appended to the end of the slice. Furthermore, the
`handle` method executed only a callback in the first matched route,
ignoring any later updates made with SUBSCRIBE.

client: Use a map for the underlying store in messageHandlers

---

.github/workflows/bisquitt-tests.yaml

Adds the latest Go version to job matrix.

Add Go 1.18 in job matrix

---

.github/workflows/bisquitt-docker.yaml
.github/workflows/bisquitt-tests.yaml

Adds a new workflow file to build and push bisquitt Docker image. The workflow runs whenever a tag is pushed. For it to work, we must add two secrets to our repository:
* `DOCKERHUB_USERNAME`
* `DOCKERHUB_TOKEN`
I'm making use of the existing Makefile targets to build and push the image. To get the version information, the workflow relies on `version.txt` and disregards the tag name. This may lead to some weird outcomes, such as accidentally updating an old tagged image if someone pushes a new tag which hasn't had `version.txt` updated. I'm not sure how I feel about this.
Closes #21.

Add workflow file to build and push the Docker image

---

client/client.go

If an error appears inside any of the the `Client.group` goroutines,
the failed goroutine returns a non-nil `error` and the whole
`Client.group` is cancelled using `Client.groupCtx`. I.e. this condition
is signalized by closed `Client.groupCtx.Done()` channel.
The `Client`'s API functions should get the error using
`Client.group.Wait()` call and return it to the caller.
There's no point in returning `context.Canceled` because
`Client.group.Wait()` must eventually return in such condition.

client: Fix errors returned from API functions

---

client/client_test.go
client/net.go
client/subscribe_transaction.go
client/unsubscribe_transaction.go
cmd/bisquitt-sub/actions.go
gateway/connect_transaction.go
gateway/gateway_test.go
gateway/handler.go
gateway/subscribe_transaction.go
packets1/auth.go

According to the Go convention, all `error`s returned from functions
should begin with a lower case letter.
On the contrary, errors logged using `util.Logger.Error` should be
capitalized.
+ one unrelated one-line correction which doesn't deserve its own PR...

Uncapitalize all error strings

---

util/conn_with_context.go

When context is closed because of an error, this error should also be returned from `ConnWithContext.{Read,Write}()` because it could be used by the caller.
This commit fixes e.g. a bug in `bisquitt-sub` where on some internal errors, only "context canceled" error is printed on the console, instead of the real error which caused the cancellation.

Return specific context error from `ConnWithContext.{Read,Write}()`

---

gateway/handler1.go

Context is not used anywhere in the function, we can safely remove it.
Merge after #32

gateway: Remove unused `Context` from `handleUnsubscribe()`

---

gateway/gateway.go
gateway/handler1.go

Handler should be a self-contained component which correctly handles all
possible errors. There's no reason to return error to the caller of
`handler1.run()` (and the returned error is unused anyway in the current
code).
Merge after #32

gateway: Do not return error from `handler1.run()`

---

client/client_test.go
client/disconnect_transaction.go
client/ping_transaction.go
client/publish_qos1_transaction.go
client/publish_qos2_transaction.go
client/register_transaction.go
client/subscribe_transaction.go
client/unsubscribe_transaction.go
gateway/broker_publish_transaction.go
gateway/connect_transaction.go
gateway/handler1.go
gateway/subscribe_transaction.go
transactions/transaction_store.go

The MQTT-SN v.2.0 specification uses the term "packet" instead of "message". This commit replaces "message", "msg" with "packet", "pkt" wherever it's not a terminus technicus from MQTT-SN v.1.2.

Replace "message" with "packet"

---

packets1/packets1.go
packets1/willmsgupd.go
packets1/willmsgupd_test.go
packets1/willtopicupd.go
packets1/willtopicupd_test.go

The name of the packets are `WILLMSGUPD` and `WILLTOPICUPD` and the corresponding structs should be named the same.

Rename `Will{Msg,Topic}Update` to `Will{Msg,Topic}Upd`

---

client/client.go
client/client_test.go
gateway/gateway_test.go
packets1/subscribe.go
packets1/subscribe_test.go
packets1/unsubscribe.go
packets1/unsubscribe_test.go
packets1/willtopicupd.go
packets1/willtopicupd_test.go

Topic should be a well-formed string, it doesn't make sense to define it as a byte array.
Merge after #38

Make `Topic` type `string`

---

packets/header.go

After the packets (de)serialization API change from `io.Reader` to `[]byte`, these functions are not used anymore.

packets: Remove unused `Read*(io.Reader)` functions

---

client/client.go
client/client_test.go
gateway/gateway_test.go
gateway/handler1.go
gateway/subscribe_transaction.go
packets1/connect.go
packets1/connect_test.go
packets1/publish.go
packets1/publish_test.go
packets1/suback.go
packets1/suback_test.go
packets1/subscribe.go
packets1/subscribe_test.go
packets1/unsubscribe.go
packets1/unsubscribe_test.go

Arguments order should match the order of the packet's fields as defined
in the specification. Flags are placed at the end of the args list.

packets1: Unify constructors arguments order

---

packets1/advertise.go
packets1/auth.go
packets1/connack.go
packets1/connect.go
packets1/disconnect.go
packets1/gwinfo.go
packets1/pingreq.go
packets1/puback.go
packets1/pubcomp.go
packets1/publish.go
packets1/pubrec.go
packets1/pubrel.go
packets1/regack.go
packets1/register.go
packets1/searchgw.go
packets1/suback.go
packets1/subscribe.go
packets1/unsuback.go
packets1/unsubscribe.go
packets1/willmsg.go
packets1/willmsgresp.go
packets1/willmsgupd.go
packets1/willtopic.go
packets1/willtopicresp.go
packets1/willtopicupd.go

Makes structs more readable and conforming to the specification.
- add `Flags` and `Fields` comments
- change structs fields order to reflect the order of packet fields in the specification
...i.e. make fields order the same as constructor args order introduced in #41

packets1: Unify structs fields order

---

packets1/packets1.go
packets1/packets1_test.go
packets1/willmsgreq.go

Possible `pkt.Unpack()` error was incorrectly ignored in `ReadPacket()`. First commit fixes it and also adds a new test for incorrect packet type unmarshalling.
This `ReadPacket()` fix also revealed a bug in `WillMsgReq.Unpack()`. It's a one-line fix, so I include it in this PR also.

packets1: Return `Unpack()` errors from `ReadPacket()`

---

client/client_test.go
gateway/connect_transaction.go
packets1/auth.go

`DecodePlain` takes `*Auth` as a parameter anyway, so it would be better to declare it as `Auth` method.

Make `packets1.DecodePlain` an `Auth` method

---

packets1/connect.go
packets1/connect_test.go

This PR makes `packets1.Connect` code fully covered by unit tests. Two minor code fixes are also added because I don't think they deserve their own PRs.
The first commit adds a protocol version check to `Connect.Unpack()` - if the version is not 1, we should not parse the packet at all because we would get garbage data.

packets1: Add full-coverage `Connect` unit tests

---

packets1/advertise_test.go
packets1/auth.go
packets1/auth_test.go
packets1/connack_test.go

This PR makes `packets1.{Advertise,Auth,Connack}` code fully covered by unit tests. The second commit contains a small fix not deserving its own PR.

packets1: Add full-coverage `Advertise`, `Auth`, `Connack` unit tests 

---

packets1/disconnect_test.go
packets1/gwinfo_test.go
packets1/pingreq_test.go
packets1/pingresp_test.go

This PR makes packets1.{Disconnect,GwInfo,Ping*} code fully covered by unit tests.

packets1: Add full-coverage `Disconnect`, `GwInfo`, `Ping*` unit tests

---

packets1/willtopicupd.go
packets1/willtopicupd_test.go

Like in `WILLTOPIC`, the `WILLTOPICUPD` packet must not contain `Flags` if `WillMsg` length is zero.
The old implementation inserts `Flags` field into the packet regardless of `WillMsg`. This PR introduces the right behavior and improved `WillTopicUpd` tests.

packets1: Fix `WILLTOPICUPD` implementation

---

packets1/property_message_id_test.go
packets1/willmsg_test.go
packets1/willmsgreq_test.go
packets1/willmsgresp_test.go
packets1/willmsgupd_test.go
packets1/willtopic.go
packets1/willtopic_test.go
packets1/willtopicreq_test.go
packets1/willtopicresp_test.go

The first commit improves the way `WillTopic` packets are stringified by `String()` (similar to the first commit of #51). 
The other commits make `packets1.Will*` and `MessageIDProperty` code fully covered by unit tests.

packets1: Add full-coverage `Will*` and `MessageIDProperty` unit tests

---

packets/header.go
packets2/packets2.go
packets2/packets2_test.go
packets2/property_packet_id.go
packets2/property_packet_id_test.go

The PR adds a common code used by various packets structs implementations which will follow in other PRs.

Add `packets2` package and packets' common parts

---

packets2/advertise.go
packets2/advertise_test.go
packets2/gwinfo.go
packets2/gwinfo_test.go
packets2/packets2.go
packets2/searchgw.go
packets2/searchgw_test.go

PR adds gateway-related packets: `Advertise`, `GwInfo`, `SearchGw`.

packets2: Add gateway-related packets

---

packets2/packets2.go
packets2/property_packet_id_test.go
packets2/puback.go
packets2/puback_test.go
packets2/pubcomp.go
packets2/pubcomp_test.go
packets2/publish.go
packets2/publish_test.go
packets2/pubrec.go
packets2/pubrec_test.go
packets2/pubrel.go
packets2/pubrel_test.go

PR adds gateway-related packets: `Publish`, `Puback`, `Pubrec`, `Pubrel`, `Pubcomp`.

packets2: Add publish-related packets

---

packets2/auth.go
packets2/auth_test.go
packets2/connack.go
packets2/connack_test.go
packets2/connect.go
packets2/connect_test.go
packets2/disconnect.go
packets2/disconnect_test.go
packets2/packets2.go
packets2/pingreq.go
packets2/pingreq_test.go
packets2/pingresp.go
packets2/pingresp_test.go

PR adds connection-related packets: `Auth`, `Connect`, `Connack`, `Disconnect`, `Pingresp`, `Pingreq`.

packets2: Add connection-related packets

---

packets2/packets2.go
packets2/regack.go
packets2/regack_test.go
packets2/register.go
packets2/register_test.go
packets2/suback.go
packets2/suback_test.go
packets2/subscribe.go
packets2/subscribe_test.go
packets2/unsuback.go
packets2/unsuback_test.go
packets2/unsubscribe.go
packets2/unsubscribe_test.go

PR adds register and subscribe-related packets: `Register`, `Regack`, `Subscribe`, `Suback`, `Unsubscribe`, `Unsuback`.

packets2: Add register and subscribe-related packets

---

packets1/willtopicupd.go
packets1/willtopicupd_test.go

Field name used in `WillTopicUpd.String` output didn’t match the struct itself.

packets1: Fix field name in `WillTopicUpd.String`

---

client/client.go
cmd/bisquitt-pub/actions.go
cmd/bisquitt-pub/application.go
cmd/bisquitt-sub/actions.go
cmd/bisquitt-sub/application.go
cmd/bisquitt/actions.go
cmd/bisquitt/application.go
gateway/gateway.go
go.mod
go.sum
util/pskclient.go

Added support for PSK (DTLS preshared-key) in BISQUITT, enhancing security options. This feature integrates an HTTP API to obtain PSK keys, introducing API caching to optimize performance. With this update, users have the flexibility to choose between certificates and PSK for authentication, though both methods cannot be used simultaneously.
- Implemented PSK (DTLS preshared-key) support in BISQUITT.
- Integrated HTTP API for fetching PSK keys.
- Introduced API caching mechanism to reduce redundant API calls.
- Provided option for users to choose between certificates and PSK for authentication.
Notes:
- Users must select either certificates or PSK for authentication; simultaneous use of both methods is not supported.
- An example implementation of the HTTP API will be published in another …

Add DTLS PSK support
